name: mobile_odoo_assistances
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  geolocator: ^9.0.2
  http: ^0.13.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/top_left_logo.png


flutter_launcher_icons:

  android: true
  ios: true


  image_path: "assets/images/app_icon.png"

